Java05. ДЗ 02, Кузнецов Александр
AlexVanGogen/spbau-java-course pull request #3
Opened 2018-03-28 12:30 UTC by AlexVanGogen

@dsavvinov

2018-04-16 17:23 UTC, dsavvinov requested changes
На будущее -- я абсолютно нормально отношусь к уточняющим вопросам в духе "А можно ли использовать класс X из JDK?" :) Мы ограничиваем использование стандартной библиотеки только потому, что там иногда есть классы, полностью решающие задание (например, `HashMap` для данного задания), а не для того, чтобы поиздеваться над вами и заставить переписать хэширование строк) Разумное использование JDK вобщем-то, скорее поощряется, чем осуждается :)

Так-то все хорошо, только почини хэширование, пожалуйста (я на паре упоминал еще некоторые распространенные ошибки связанные с хэшами/индексами, не забудь про них)

2018-04-16 17:23 UTC, dsavvinov commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +    private final int MINIMAL_TABLE_SIZE = 1001;
А почему так много?

2018-04-16 17:23 UTC, dsavvinov commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +    private final int DEFAULT_POLYNOMIAL_HASH_PARAMETER = 2;
По-моему, не очень удачный выбор, учитывая, что в качестве модуля выступает MAX_INT.

2018-04-16 17:23 UTC, dsavvinov commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +    private int hashOf(final String key, final int hashParameter) {
Ну `hashCode`-то можно было использовать :)

2018-04-16 17:23 UTC, dsavvinov commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +        return result % tableSize;
`result` может переполниться и стать отрицательным, тогда весь метод тоже вернет отрицатлеьное число, и там где-нибудь `ArrayIndexOutOfBoundException` стрельнет

2018-04-16 17:23 UTC, dsavvinov commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +                while (currentNode != null) {
Minor: на мой вкус, в таких ситуациях `for` лучше -- так очевидней, что цикл в каком-то смысле изоморфен циклу с индексами: есть подобие итератора (currentNode), выход из цикла зависит только от итератора (currentNode != null) и на *каждой* итерации итератор изменяется тривиальным образом.

Но тут нет единого мнения, так что это скорее идея, чем совет.

2018-04-20 18:49 UTC, AlexVanGogen commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +    private final int MINIMAL_TABLE_SIZE = 1001;
В этом нет никакой скрытой логики, просто взял какое-то интересное число

2018-04-20 18:49 UTC, AlexVanGogen commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +    private final int DEFAULT_POLYNOMIAL_HASH_PARAMETER = 2;
Мягко говоря :)

2018-04-20 18:49 UTC, AlexVanGogen commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +    private int hashOf(final String key, final int hashParameter) {
Я пропустил ту практику, на которой обсуждалось это ДЗ, и поэтому думал, что __все__ нужно реализовать самому. Хотя, это все равно небесполезный опыт

2018-04-20 18:49 UTC, AlexVanGogen commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +        return result % tableSize;
Да, решил проблему

2018-04-20 18:49 UTC, AlexVanGogen commented on hw-02-dictionary/src/main/java/ru/spbau/mit/javacourse/dictionary/DictionaryImpl.java
> +                while (currentNode != null) {
Почему-то не подумал о возможности использовать тут `for`, мне так тоже больше нравится

2018-04-23 08:06 UTC, dsavvinov approved these changes
-1б за багу с отрицательными хэшами, итого 9б, зачтено.

2018-04-23 16:59 UTC, merged