Java05. ДЗ 03, Кузнецов Александр
AlexVanGogen/spbau-java-course pull request #4
Opened 2018-04-11 12:22 UTC by AlexVanGogen

@dsavvinov

2018-04-18 08:51 UTC, dsavvinov requested changes
Копирую замечание к работам других твоих одногруппников:

Мне не нравится, что нет никакой защиты от data corruption -- мы безусловно доверяем поступающему потоку байтов, и если какой-нибудь (злонамеренный) дурак подсунул какую-нибудь фигню, то мы в лучшем случае развалимся с рандомным исключением откуда-то из кишок библиотеки. В худшем -- десериализуем какую-нибудь ерунду.

Я не настаиваю на том, чтобы ты покрывал все возможные несчастья, которые могли произойти с потоком байтов. Но хочу услышать некоторое подобие спецификации: устное перечисление возможных проблем + поведение программы при таких невалидных инпутах. Если текущее поведение в каких-то случаях кажется тебе совсем неразумным, то лучше сразу исправить :)

2018-04-26 21:16 UTC, AlexVanGogen commented
Напишу, какую дичь можно отследить c моим алгоритмом сериализации.
- Входной поток внезапно оборвался. Алгоритму нужны данные для построения, а их нет => получаю EOFException.
- Количество слов с заданным префиксом (значение, которое прямо так и записывается при сериализации) отличается от количества слов, которые были десериализованы на самом деле. Это говорит либо о том, что некорректно сериализованы признаки того, является ли вершина терминальной, либо о том, что некорректно записано количество слов с заданным префиксом. Вот это можно проверить, и этого на данный момент у меня нет.
- Можно также отслеживать ситуации, когда дерево закончено, а в потоке еще что-то есть, и считать, что это тоже испорченный поток.

А вот что нельзя проверить, так это недопустимые символы. Я вообще нигде не записываю в поток никакие символы бора. То есть, любой бор, изоморфный нашему с точки зрения алфавита, будет десериализован корректно и, более того, алфавит этого бора будет отображен в наш алфавит. Например, поток данных, содержащих некоторый бор со словами "@" и "@$@", будет десериализован как бор со словами, например, "a" и "aba". Чтобы это исправить, нужно немного переписать (де-)сериализацию.

2018-04-26 21:52 UTC, dsavvinov commented
Ну и норм.

Зачтено, 10б

2018-04-26 22:25 UTC, AlexVanGogen commented
Эх, а я уже и исправил все :(

2018-05-16 15:13 UTC, merged